### ISSUE TITLE
Task idea

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/snakemake-tutorial-scratch#1]
Here's what I'm thinking for the task that the tutorial will do:

1. download the PGDL predictions from this data release: https://www.sciencebase.gov/catalog/item/5e5d0bb9e4b01d50924f2b36
2. unzip the file
3. for several sites (3 maybe), combine the data into one file
4. visualize the predictions

**Comment by jsadler2** [comment]
Here's what the `analyze.py` script produces.
![doy_plot](https://user-images.githubusercontent.com/6943441/153625087-9827662e-830e-4be6-8f9c-372ce3c1fca2.png)

**Comment by jsadler2** [comment]
The idea would then be to convert what is in analyze.py into a snakemake workflow with wildcards for the site ids.

**Comment by AndyMcAliley** [comment]
I like this workflow! It seems like the right amount of complexity for an introductory training module. So, if I understand correctly, the Snakemake pipeline would look something like this:

```mermaid
flowchart TB
SB(ScienceBase) --> D[Download]
D --> Z("pgdl_predictions_[...].zip")
Z --> U[Unzip]
U --> U1("pgdl_nhdhr_{lake_id1}_temperatures.csv")
U --> U2("pgdl_nhdhr_{lake_id2}_temperatures.csv")
U --> U3("pgdl_nhdhr_{lake_id3}_temperatures.csv")
U1 --> C1[calc_doy_means]
U2 --> C2[calc_doy_means]
U3 --> C3[calc_doy_means]
C1 -->  M1("doy_{lake_id1}.csv")
C2 --> M2("doy_{lake_id2}.csv")
C3 --> M3("doy_{lake_id3}.csv")
M1 --> C[combine_site_files]
M2 --> C
M3 --> C
C --> CD(combined_doy.csv)
CD --> P[plot_doy_means]
P --> DP(doy_plot.png)

classDef operation fill:#cee,stroke:#000,stroke-width:1px
classDef file fill:#eed,stroke:#000,stroke-width:1px
class D,U,C1,C2,C3,C,P operation
class Z,U1,U2,U3,M1,M2,M3,CD,DP file
```

**Comment by wdwatkins** [comment]
Sounds good to me

**Comment by amsnyder** [comment]
@AndyMcAliley - do you think we can close out this issue at this stage?

**Comment by AndyMcAliley** [comment]
Sure!
