### ISSUE TITLE
Add instructions for fork/clone of base repo and issues

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/snakemake-tutorial-scratch#16]
We need to add instructions to issue 0 (or maybe somewhere else) explaining how the 'student' of this learning module should clone this repo. We need to:
- create our official code base to start the work from  so we can tell them to clone the appropriate repo
- look into turning the issue drafts from .md files into actual issues (and note that issues won't copy when the student forks)

**Comment by AndyMcAliley** [comment]
We've settled on not turning the .md files into actual issues, and instructions for cloning are in the main README, so I'm closing this.
