### ISSUE TITLE
update issues to final version

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/snakemake-tutorial-scratch#28]
We should update the issue markdown files once they are finalized in the introduction repo. I think it would be easiest just to copy/paste and overwrite all the files at once after we think they are finalized.

Another option is to delete them from this repo, and just keep this as a code answer key so that we don't have to worry about it staying synchronized with snakemake-introduction.

**Comment by AndyMcAliley** [comment]
I like the idea of deleting the issues here and letting this repo be just the answer key.
