### ISSUE TITLE
Splitting Script into Functions

### ISSUE THREAD

**Issue by ted80810** [USGS-R/snakemake-tutorial-scratch#5]
This issue is to track changes to the scripts.

**Comment by ted80810** [comment]
After speaking with @AndyMcAliley, the first step looks like it should be to separate each function into a script. This way we can utilize snakemake's script directive to track changes in the scripts and call individual scripts in the rule. Below is a first pass for separating the function for fetching the data from ScienceBase:

 `import os
from sciencebasepy import SbSession

def sb_get(item_id, sb_data_file=None, destination_dir='.'):
    """
    Download an item from ScienceBase by ID. 
    Written by @AndyMcAliley

    :param item_id: ScienceBase ID of item to download
    :param sb_data_file: Name of file to download. If None, download all files. (Default value = None)
    :param destination_dir: directory to save to (Default value = '.')
    :returns: ScienceBase JSON response

    """
    sb_session = SbSession()
    if not (sb_session.ping()['result'] == 'OK'):
        raise ConnectionError('ScienceBase ping unsuccessful')
    # If data are public, no need to log in
    # if not sb_session.is_logged_in():
        # sb_session.login()

    item_json = sb_session.get_item(item_id)
    if sb_data_file is None:
        response = sb_session.get_item_files(item_json, destination=destination_dir)
    else:
        all_file_info = sb_session.get_item_file_info(item_json)
        file_found = False
        for file_info in all_file_info:
            if file_info['name'] == sb_data_file:
                file_found = True
                response = sb_session.download_file(file_info['url'], file_info['name'], destination_dir)
        if not file_found:
            raise FileNotFoundError(f'{sb_data_file} not found on ScienceBase')

    return response

def main():
    sb_item = "5e5d0bb9e4b01d50924f2b36"
    sb_file = "pgdl_predictions_04_N45.50-48.00_W92.00-93.00.zip"
    out_dir = "out_data/"
    sb_get(sb_item, sb_file, out_dir)
    
if __name__ == "__main__":`

**Comment by AndyMcAliley** [comment]
Thanks, Ted! This is a good first step towards splitting out the parts of the workflow into separate scripts. I assume that this is missing one line at the bottom that would call `main()`.

This is nice because it's simple. The Snakemake rule would call this script, and the script would download the appropriate file. I think that, in the tutorial, it could work well to start here. Then, as a later step in the tutorial, we can move the hardcoded sb_item, sb_file, and out_dir out of the script and into the Snakefile.

**Comment by ted80810** [comment]
> Thanks, Ted! This is a good first step towards splitting out the parts of the workflow into separate scripts. I assume that this is missing one line at the bottom that would call `main()`.
> 
> This is nice because it's simple. The Snakemake rule would call this script, and the script would download the appropriate file. I think that, in the tutorial, it could work well to start here. Then, as a later step in the tutorial, we can move the hardcoded sb_item, sb_file, and out_dir out of the script and into the Snakefile.

Yes, that's correct. I was also contemplating if the arguments for the functions should be the snakemake inputs. Do you think that is too complicated for this tutorial or a good process to illustrate in the tutorial?

**Comment by AndyMcAliley** [comment]
I think that would be good to include in the tutorial. I don't think that these arguments would be Snakemake `inputs` for the rule that calls this script, though. `sb_file` and `out_dir` could be inferred from the rule's `output`, and `sb_item` can be specified in `params`.

**Comment by AndyMcAliley** [comment]
Closed by #7
